server {
    listen 80;
    server_name tools.haobanfa.online;
    root /www/wwwroot/tools.haobanfa.online/public;
    index index.php index.html;

    client_max_body_size 20m;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_pass unix:/tmp/php-cgi-81.sock;
    }

    location ~ /\.(?!well-known) {
        deny all;
    }
}
